# Generated by Django 3.2.16 on 2022-11-22 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_coments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coments',
            old_name='product',
            new_name='post',
        ),
    ]
